# Tugas 8 Maret

### Hitunglah:

    2*A
    2+A
    A+B
    A-B
    determinan A
    invers dari B, simpan jadi matriks D
    transpose D
    nilai eigen dan vektor eigen dari A dan B

In [1]:
import numpy as np

In [8]:
A = np.array([[1, 2], [7,8]])
B = np.array([[3, 5], [1,6]])

In [9]:
print(2 * A, "--> 2*A") # 2*A
print("")
print(2 + A, "--> 2+A") # 2+A
print("")
print(A + B, "--> A+B") # A+B
print("")
print(A - B, "--> A-B") # A-B
print("")

print('determinan matriks A =', np.linalg.det(A)) # Determinan matriks A
print("")

D = (np.linalg.inv(B)) # Invers B di simpan menjadi matriks D
print(D, "--> Matriks D (invers dari matriks B)")
print("")

tp = np.transpose(D) # Transpose matriks D
print(tp, "--> Transpose matriks D")
print("")

# nilai eigen dan vektor eigen dari matriks A dan B
print(np.linalg.eig(A)[0], "--> nilai eigen dari matriks A") # nilai eigen dari matriks A
print("")
print(np.linalg.eig(A)[1], "--> vektor eigen dari matriks A") # vektor eigen dari matriks A
print("")
print(np.linalg.eig(B)[0], "--> nilai eigen dari matriks B") # nilai eigen dari matriks B
print("")
print(np.linalg.eig(B)[1], "--> vektor eigen dari matriks B") # vektor eigen dari matriks B

[[ 2  4]
 [14 16]] --> 2*A

[[ 3  4]
 [ 9 10]] --> 2+A

[[ 4  7]
 [ 8 14]] --> A+B

[[-2 -3]
 [ 6  2]] --> A-B

determinan matriks A = -6.0

[[ 0.46153846 -0.38461538]
 [-0.07692308  0.23076923]] --> Matriks D (invers dari matriks B)

[[ 0.46153846 -0.07692308]
 [-0.38461538  0.23076923]] --> Transpose matriks D

[-0.62347538  9.62347538] --> nilai eigen dari matriks A

[[-0.77640358 -0.22592838]
 [ 0.63023605 -0.97414391]] --> vektor eigen dari matriks A

[1.8074176 7.1925824] --> nilai eigen dari matriks B

[[-0.97271381 -0.76626443]
 [ 0.23200828 -0.64252535]] --> vektor eigen dari matriks B


#### perbedaan dari B*D (perkalian antar entry di B dan D) dan BD (perkalian matriks B dan D)

In [7]:
print(B * D, "--> B*D") # Perkalian antar entry (B*D)
print("")
print(np.matmul(B,D), "--> BD") # Perkalian matriks B dan D (BD)

[[ 1.38461538 -1.92307692]
 [-0.07692308  1.38461538]] --> B*D

[[1.00000000e+00 0.00000000e+00]
 [5.55111512e-17 1.00000000e+00]] --> BD


    perbedaaanya untuk perkalian antar entry yang dikalikan adalah bilangan di baris 1 matriks B dikalikan dengan bilangan di baris 1 matriks D, bilangan di kolom 2 matriks B dikalikan bilangan di kolom 2 matriks D. Sedangkan perkalian matriks yang dikalikan adalah baris matriks B dengan kolom matrik D dan kolom matriks B dengan baris matrik D.